const fs = require("fs");
const { release } = require("os");

function transformTmdbJson(tmdbData) {
  // Comprehensive TMDB genre ID to name mapping
  const genreMap = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Science Fiction",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western",
  };

  return tmdbData.results.map((movie) => ({
    id: movie.id.toString(),
    title: movie.title,
    description: movie.overview,
    thumbnailUrl: `https://image.tmdb.org/t/p/original${movie.poster_path}`,
    backdrop_path: `https://image.tmdb.org/t/p/original${movie.backdrop_path}`,
    videoUrl:
      "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    categories: movie.genre_ids.map((id) => genreMap[id] || "Unknown"),
    type: "movie",
    releaseDate: movie.release_date.split("-")[0],
    rating: movie.vote_average / 2,
    tags: movie.genre_ids.map((id) =>
      (genreMap[id] || "unknown").toLowerCase()
    ),
  }));
}

// Example usage with the provided JSON
const tmdbData = {
  results: [
    {
      adult: false,
      backdrop_path: "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
      genre_ids: [10751, 35, 12, 14, 28],
      id: 950387,
      original_language: "en",
      original_title: "A Minecraft Movie",
      overview:
        "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
      popularity: 713.0295,
      poster_path: "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
      release_date: "2025-03-31",
      title: "A Minecraft Movie",
      video: false,
      vote_average: 6.5,
      vote_count: 1385,
    },
    {
      adult: false,
      backdrop_path: "/j0NUh5irX7q2jIRtbLo8TZyRn6y.jpg",
      genre_ids: [27, 9648],
      id: 574475,
      original_language: "en",
      original_title: "Final Destination Bloodlines",
      overview:
        "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
      popularity: 551.0284,
      poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
      release_date: "2025-05-09",
      title: "Final Destination Bloodlines",
      video: false,
      vote_average: 7.117,
      vote_count: 356,
    },
    {
      adult: false,
      backdrop_path: "/tyfO9jHgkhypUFizRVYD0bytPjP.jpg",
      genre_ids: [10751, 14],
      id: 447273,
      original_language: "en",
      original_title: "Snow White",
      overview:
        "Following the benevolent King's disappearance, the Evil Queen dominated the once fair land with a cruel streak. Princess Snow White flees the castle when the Queen, in her jealousy over Snow White's inner beauty, tries to kill her. Deep into the dark woods, she stumbles upon seven magical dwarves and a young bandit named Jonathan. Together, they strive to survive the Queen's relentless pursuit and aspire to take back the kingdom.",
      popularity: 299.7977,
      poster_path: "/oLxWocqheC8XbXbxqJ3x422j9PW.jpg",
      release_date: "2025-03-12",
      title: "Snow White",
      video: false,
      vote_average: 4.305,
      vote_count: 915,
    },
    {
      adult: false,
      backdrop_path: "/cJvUJEEQ86LSjl4gFLkYpdCJC96.jpg",
      genre_ids: [10752, 28],
      id: 1241436,
      original_language: "en",
      original_title: "Warfare",
      overview:
        "A platoon of Navy SEALs embarks on a dangerous mission in Ramadi, Iraq, with the chaos and brotherhood of war retold through their memories of the event.",
      popularity: 284.6892,
      poster_path: "/srj9rYrjefyWqkLc6l2xjTGeBGO.jpg",
      release_date: "2025-04-09",
      title: "Warfare",
      video: false,
      vote_average: 7.243,
      vote_count: 409,
    },
    {
      adult: false,
      backdrop_path: "/1p5aI299YBnqrEEvVGJERk2MXXb.jpg",
      genre_ids: [28, 12, 53],
      id: 575265,
      original_language: "en",
      original_title: "Mission: Impossible - The Final Reckoning",
      overview:
        "Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Hunt's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
      popularity: 237.051,
      poster_path: "/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg",
      release_date: "2025-05-17",
      title: "Mission: Impossible - The Final Reckoning",
      video: false,
      vote_average: 7.1,
      vote_count: 198,
    },
    {
      adult: false,
      backdrop_path: "/jRvhP4AfFnJ03lCQhp1fie7XPSd.jpg",
      genre_ids: [28, 53],
      id: 977294,
      original_language: "en",
      original_title: "Tin Soldier",
      overview:
        "An ex-special forces operative seeks revenge against a cult leader who has corrupted his former comrades, the Shinjas. This leader, known as The Bokushi, promises veterans a purpose and protection, but is revealed to be a destructive influence. The ex-soldier, Nash Cavanaugh, joins forces with military operative Emmanuel Ashburn to infiltrate the Bokushi's fortress and expose his reign of terror",
      popularity: 209.1543,
      poster_path: "/lFFDrFLXywFhy6khHes1LCFVMsL.jpg",
      release_date: "2025-05-22",
      title: "Tin Soldier",
      video: false,
      vote_average: 5.214,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
      genre_ids: [10751, 35, 878],
      id: 552524,
      original_language: "en",
      original_title: "Lilo & Stitch",
      overview:
        "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
      popularity: 368.4068,
      poster_path: "/tUae3mefrDVTgm5mRzqWnZK6fOP.jpg",
      release_date: "2025-05-17",
      title: "Lilo & Stitch",
      video: false,
      vote_average: 7.1,
      vote_count: 78,
    },
    {
      adult: false,
      backdrop_path: "/bIh56F8e5EaZ3r2nD1hXAOisItZ.jpg",
      genre_ids: [12, 10751, 99],
      id: 1094473,
      original_language: "fr",
      original_title: "Bambi, l'histoire d'une vie dans les bois",
      overview:
        "The life of Bambi, a male roe deer, from his birth through childhood, the loss of his mother, the finding of a mate, the lessons he learns from his father, and the experience he gains about the dangers posed by human hunters in the forest.",
      popularity: 176.5245,
      poster_path: "/vWNVHtwOhcoOEUSrY1iHRGbgH8O.jpg",
      release_date: "2024-10-16",
      title: "Bambi: A Life in the Woods",
      video: false,
      vote_average: 5.955,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
      genre_ids: [28, 878, 12],
      id: 986056,
      original_language: "en",
      original_title: "Thunderbolts*",
      overview:
        "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
      popularity: 191.9705,
      poster_path: "/m9EtP1Yrzv6v7dMaC9mRaGhd1um.jpg",
      release_date: "2025-04-30",
      title: "Thunderbolts*",
      video: false,
      vote_average: 7.478,
      vote_count: 962,
    },
    {
      adult: false,
      backdrop_path: "/bVm6udIB6iKsRqgMdQh6HywuEBj.jpg",
      genre_ids: [53, 28],
      id: 1233069,
      original_language: "de",
      original_title: "Exterritorial",
      overview:
        "When her son vanishes inside a US consulate, ex-special forces soldier Sara does everything in her power to find him — and uncovers a dark conspiracy.",
      popularity: 169.2926,
      poster_path: "/jM2uqCZNKbiyStyzXOERpMqAbdx.jpg",
      release_date: "2025-04-29",
      title: "Exterritorial",
      video: false,
      vote_average: 6.689,
      vote_count: 371,
    },
    {
      adult: false,
      backdrop_path: "/4A5HH9HkCPqAwyYL6CnA0mxbYjn.jpg",
      genre_ids: [28, 80, 53, 18],
      id: 1144430,
      original_language: "fr",
      original_title: "Balle perdue 3",
      overview:
        "Car genius Lino returns to conclude his vendetta against Areski and the corrupt commander who ruined their lives in this turbo-charged trilogy finale.",
      popularity: 161.4838,
      poster_path: "/lCI5y1KkjgMoTkZiCleqji00XeE.jpg",
      release_date: "2025-05-06",
      title: "Last Bullet",
      video: false,
      vote_average: 6.833,
      vote_count: 129,
    },
    {
      adult: false,
      backdrop_path: "/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg",
      genre_ids: [28, 14, 12],
      id: 324544,
      original_language: "en",
      original_title: "In the Lost Lands",
      overview:
        "A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where she and her guide, the drifter Boyce, must outwit and outfight both man and demon.",
      popularity: 159.5093,
      poster_path: "/dDlfjR7gllmr8HTeN6rfrYhTdwX.jpg",
      release_date: "2025-02-27",
      title: "In the Lost Lands",
      video: false,
      vote_average: 6.383,
      vote_count: 386,
    },
    {
      adult: false,
      backdrop_path: "/kFXtAwJYbRTqiyQpE9kDc8qEP3X.jpg",
      genre_ids: [28, 53],
      id: 1225915,
      original_language: "hi",
      original_title: "ज्वेल थीफ़ - The Heist Begins",
      overview:
        "In this high-octane battle of wits and wills, ingenious con artist Rehan devises a diamond heist while trying to outsmart Rajan, his sadistic adversary.",
      popularity: 118.2265,
      poster_path: "/eujLbO0kf1eqWC8XpHUJdtAVW2J.jpg",
      release_date: "2025-04-24",
      title: "Jewel Thief - The Heist Begins",
      video: false,
      vote_average: 6.78,
      vote_count: 41,
    },
    {
      adult: false,
      backdrop_path: "/dJ1JpHuTCRxtGpRq8bQzk2jBqTi.jpg",
      genre_ids: [14, 12, 10751],
      id: 896536,
      original_language: "en",
      original_title: "The Legend of Ochi",
      overview:
        "In a remote village on the island of Carpathia, a shy farm girl named Yuri is raised to fear an elusive animal species known as ochi. But when Yuri discovers a wounded baby ochi has been left behind, she escapes on a quest to bring him home.",
      popularity: 202.7812,
      poster_path: "/wVujUVvY4qvKARAslItQ4ARKqtz.jpg",
      release_date: "2025-04-18",
      title: "The Legend of Ochi",
      video: false,
      vote_average: 6.017,
      vote_count: 58,
    },
    {
      adult: false,
      backdrop_path: "/nAxGnGHOsfzufThz20zgmRwKur3.jpg",
      genre_ids: [27, 53],
      id: 1233413,
      original_language: "en",
      original_title: "Sinners",
      overview:
        "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
      popularity: 112.8829,
      poster_path: "/jYfMTSiFFK7ffbY2lay4zyvTkEk.jpg",
      release_date: "2025-04-16",
      title: "Sinners",
      video: false,
      vote_average: 7.6,
      vote_count: 758,
    },
    {
      adult: false,
      backdrop_path: "/12tEzU0bNYKIjXXEwI5abuOotHF.jpg",
      genre_ids: [37],
      id: 710258,
      original_language: "en",
      original_title: "Rust",
      overview:
        'Infamous outlaw Harland Rust breaks his estranged grandson Lucas out of prison, after Lucas is convicted to hang for an accidental murder. The two must outrun legendary U.S Marshal Wood Helm and bounty hunter Fenton "Preacher" Lang who are hot on their tails. Deeply buried secrets rise from the ashes and an unexpected familial bond begins to form as the mismatched duo tries to survive the merciless American Frontier.',
      popularity: 107.9772,
      poster_path: "/tbJ3RkA2s6X5qrBzrYHYTxvDBui.jpg",
      release_date: "2025-05-01",
      title: "Rust",
      video: false,
      vote_average: 6.365,
      vote_count: 52,
    },
    {
      adult: false,
      backdrop_path: "/65MVgDa6YjSdqzh7YOA04mYkioo.jpg",
      genre_ids: [28, 80, 53],
      id: 668489,
      original_language: "en",
      original_title: "Havoc",
      overview:
        "When a drug heist swerves lethally out of control, a jaded cop fights his way through a corrupt city's criminal underworld to save a politician's son.",
      popularity: 108.6848,
      poster_path: "/ubP2OsF3GlfqYPvXyLw9d78djGX.jpg",
      release_date: "2025-04-25",
      title: "Havoc",
      video: false,
      vote_average: 6.527,
      vote_count: 684,
    },
    {
      adult: false,
      backdrop_path: "/6KDLAU9OnA0FhXP1av8jqavCGG9.jpg",
      genre_ids: [27],
      id: 9532,
      original_language: "en",
      original_title: "Final Destination",
      overview:
        "After a teenager has a terrifying vision of him and his friends dying in a plane crash, he prevents the accident only to have Death hunt them down, one by one.",
      popularity: 91.4464,
      poster_path: "/1mXhlQMnlfvJ2frxTjZSQNnA9Vp.jpg",
      release_date: "2000-03-17",
      title: "Final Destination",
      video: false,
      vote_average: 6.617,
      vote_count: 5973,
    },
    {
      adult: false,
      backdrop_path: "/tGjo4L15aELqZGqQH3ThZQGMKmL.jpg",
      genre_ids: [28, 12, 18],
      id: 1011477,
      original_language: "en",
      original_title: "Karate Kid: Legends",
      overview:
        "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
      popularity: 82.6855,
      poster_path: "/iXbNjhz2KU64vq6NEVVG5pIxggy.jpg",
      release_date: "2025-05-08",
      title: "Karate Kid: Legends",
      video: false,
      vote_average: 7.7,
      vote_count: 35,
    },
    {
      adult: false,
      backdrop_path: "/eDBZN0TbWkxoAB0qIDFagVcPPTN.jpg",
      genre_ids: [27, 14, 35],
      id: 1153714,
      original_language: "en",
      original_title: "Death of a Unicorn",
      overview:
        "A father and daughter accidentally hit and kill a unicorn while en route to a weekend retreat, where his billionaire boss seeks to exploit the creature’s miraculous curative properties.",
      popularity: 77.8098,
      poster_path: "/lXR32JepFwD1UHkplWqtBP1K79z.jpg",
      release_date: "2025-03-27",
      title: "Death of a Unicorn",
      video: false,
      vote_average: 6.5,
      vote_count: 242,
    },
  ],
};

// Transform and output the result
fs.writeFileSync(
  "transformedMovies.json",
  JSON.stringify(transformTmdbJson(tmdbData), null, 2),
  "utf8"
);
